[package]
name = "nanvix-python"
version = "3.12.3"
nanvix-version = "latest"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["multi-process", "single-process"]
memory = ["128mb"]

[dependencies]
cpython = "3.12.3"
